"""init

Revision ID: e38dd67c4772
Revises: 
Create Date: 2023-12-12 16:07:10.909857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38dd67c4772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinkOffer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('naviBar', sa.Boolean(), nullable=False),
    sa.Column('offer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LinkStatistic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('linkOffer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['linkOffer'], ['LinkOffer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LinkStatistic')
    op.drop_table('LinkOffer')
    # ### end Alembic commands ###
